version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kz_project
    ports:
      - "5432:5432"
    networks:
      - kz_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python src/KZ_project/webapi/app.py
    ports:
      - "5000:5000"
    volumes:
      - web-data:/kz_engine/data
    depends_on:
      - db
    networks:
      - kz_network
      - localhost

networks:
  kz_network:
  localhost:
    driver: bridge
volumes:
  postgres-data:
  web-data: